services:
  - type: web
    name: tariff-dashboard
    env: python
    buildCommand: |
      apt-get update && apt-get install -y locales
      locale-gen en_US.UTF-8
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT 